name: 'Collect Weather Data'
description: 'Collect Weather Data using wttr.in and store it in data/collected '
branding:
  icon: "activity"
  color: "green"
inputs:
  author_name:
    description: "The name of the committer"
    required: false
    default: "GitHub Actions"
  author_email:
    description: "The email address of the committer"
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"
  commit_message:
    description: "The commit message to use for the commit"
    required: false
    default: "data: Collecting New Weather Data"

runs:
  using: "composite"
  steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v3
      with:
        ref: main
  
    - name: Checkout Data Branch
      uses: actions/checkout@v3
      with:
        ref: data
        path: data

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Python dependencies
      shell: bash
      run: python -m pip install -r ${{ github.action_path }}/action-requirements.txt
    
    - name: Collect Weather Data
      id: "collect-weather-data"
      shell: bash
      run: |
        UPDATE=$(python ${{ github.action_path }}/src/actions/collect_weather_data.py
        ) || exit 1
        echo "markdown=$(echo $UPDATE)" >> $GITHUB_OUTPUT
    
    - name: Commit Changes
      id: "add-and-commit"
      uses: EndBug/add-and-commit@v9
      with:
        message: "${{ inputs.commit_message }}"
        author_name: "${{ inputs.author_name }}"
        author_email: "${{ inputs.author_email }}"
        new_branch: "data"
