name: Collect Weather Data

on:
  schedule:
    - cron: '0 0 * * *' # Esegui ogni giorno a mezzanotte UTC

  workflow_dispatch: # Permette l'avvio manuale del workflow

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Use Collect Weather Data Action
        uses: GitGinocchio/weather-prediction-github-action@main