name: Upload Utils Artifacts

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  upload-utils-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Upload utils artifacts
        uses: actions/upload-artifact@v4
        with:
          name: utils
          path: src/utils