name: Collect Weather Data

on:
  schedule:
    - cron: '0/30 * * * *' # See https://crontab.guru/#0_0/2_*_*_* for help

  workflow_dispatch: # Permette l'avvio manuale del workflow

jobs:
  collect_weather_data:
    runs-on: ubuntu-latest

    steps:
      - name: Collect Weather Data Test Dataset
        uses: GitGinocchio/weather-prediction-github-action@actions-collect
        with:
          branch_name: data-v1
          cities: New York, London, Tokyo, Pechino, Sydney, San Francisco, Berlino, Buenos Aires, Singapore, Rio de Janeiro, Miami, Dubai, Las Vegas , Marrakech, Helsinki , Oslo, Anchorage, New Orleans, Mumbai, Buffalo, Roma, Milano, Napoli, Torino, Trento, Bormio, Genova, Catania, Bologna, Firenze, Bolzano, Siena

      - name: Collect Weather Data Prod. Dataset 01.01.2025 -> ...
        uses: GitGinocchio/weather-prediction-github-action@actions-collect
        with:
          branch_name: data-01-01-2025
          cities: New York, London, Tokyo, Pechino, Sydney, San Francisco, Berlino, Buenos Aires, Singapore, Rio de Janeiro, Miami, Dubai, Las Vegas , Marrakech, Helsinki , Oslo, Anchorage, New Orleans, Mumbai, Buffalo, Roma, Milano, Napoli, Torino, Trento, Bormio, Genova, Catania, Bologna, Firenze, Bolzano, Siena, Cape Town, Nairobi, Johannesburg, Santiago, Lima, Bogotá, Quito, La Paz, Kathmandu, Chicago, Detroit, Denver, Victoria, Calgary, Vancouver, Madrid, Barcelona, Valencia, Athens, Thessaloniki, Crete, Guangzhou, Chengdu, Xi'an, Delhi, Chennai, Hyderabad, Jakarta, Hanoi, Yangon, Cairo, Alexandria, Sharm El-Sheikh, Fez, Tangier, Agadir
  