name: Collect Weather Data

on:
  schedule:
    - cron: '0 0/1 * * *' # See https://crontab.guru/#0_0/2_*_*_* for help

  workflow_dispatch: # Permette l'avvio manuale del workflow

jobs:
  collect_weather_data:
    runs-on: ubuntu-latest

    steps:
      - name: Use Collect Weather Data Action
        uses: GitGinocchio/weather-prediction-github-action@main
