name: Collect Weather Data

on:
  schedule:
    - cron: '0 0/1 * * *' # See https://crontab.guru/#0_0/2_*_*_* for help

  workflow_dispatch: # Permette l'avvio manuale del workflow

jobs:
  collect_weather_data:
    runs-on: ubuntu-latest

    steps:
      - name: Use Collect Weather Data Action
        uses: GitGinocchio/weather-prediction-github-action@actions-collect
        with:
          branch_name: data-v1
          cities: |
            New York
            London
            Tokyo
            Pechino
            Sydney
            San Francisco
            Berlino 
            Buenos Aires
            Singapore
            Rio de Janeiro
            Miami
            Dubai
            Las Vegas 
            Marrakech
            Helsinki 
            Oslo
            Anchorage
            New Orleans
            Mumbai
            Buffalo
            Roma
            Milano
            Napoli
            Torino
            Trento
            Bormio
            Genova
            Catania
            Bologna
            Firenze
            Bolzano
            Siena
